export { HTTP_STATUS } from './httpStatus.js';
export type { HttpStatusCode } from './httpStatus.js';
export {
  PLAN_CATALOG,
  PLAN_RANK,
  PLAN_SLUGS,
  BILLING_INTERVALS,
  isPaidPlan,
  isPlanSlug,
  isBillingInterval,
  monthlyCatalogPriceCents,
  annualCompareAtCents,
  annualDiscountPercent,
} from './plans.js';
export type { PlanSlug, SubscriptionStatus, BillingInterval } from './plans.js';

export const MESSAGES = {
  SUCCESS: 'Request completed successfully',
  CREATED: 'Resource created successfully',
  UPDATED: 'Resource updated successfully',
  DELETED: 'Resource deleted successfully',
  NOT_FOUND: 'Resource not found',
  VALIDATION_ERROR: 'Validation failed',
  UNAUTHORIZED: 'Authentication required',
  FORBIDDEN: 'You do not have permission to perform this action',
  INTERNAL_ERROR: 'An unexpected error occurred',
  SERVICE_UNAVAILABLE: 'Service temporarily unavailable',
  ROUTE_NOT_FOUND: 'The requested endpoint does not exist',
  DATABASE_CONNECTED: 'MongoDB connected successfully',
  DATABASE_DISCONNECTED: 'MongoDB disconnected',
  SERVER_STARTED: 'Server started successfully',
  SERVER_SHUTDOWN: 'Server shutting down gracefully',
  HEALTH_OK: 'Service is healthy',
  PRESIGNED_URL_CREATED: 'Presigned upload URL created successfully',
  VERSION_CREATED: 'Version created successfully',
  VERSION_FILES_ADDED: 'Version files updated successfully',
  VERSION_NOT_FOUND: 'Version not found',
  VERSION_DELETED: 'Version deleted successfully',
  DOWNLOAD_URL_CREATED: 'Download URL created successfully',
  REGISTERED: 'Account created successfully',
  LOGIN_SUCCESS: 'Logged in successfully',
  PLAN_NOT_FOUND: 'Plan not found',
  SUBSCRIPTION_NOT_FOUND: 'Subscription not found',
  CHECKOUT_CREATED: 'Checkout session created successfully',
  BILLING_PORTAL_CREATED: 'Billing portal session created successfully',
  SUBSCRIPTION_CANCELED: 'Subscription cancellation scheduled',
  SUBSCRIPTION_CANCELED_IMMEDIATE: 'Subscription canceled',
  SUBSCRIPTION_REACTIVATED: 'Subscription reactivated successfully',
  PLAN_CHANGED: 'Subscription plan change applied',
  ALREADY_SUBSCRIBED: 'An active paid subscription already exists',
  TRIAL_ALREADY_USED: 'Free trial has already been used for this account',
  INVALID_WEBHOOK: 'Invalid Stripe webhook signature',
  STRIPE_ERROR: 'Stripe request failed',
} as const;
